In [21]:
import numpy as np

In [ ]:
Примеры создания массивов:

In [ ]:
Из обычных списков 

In [ ]:
В данном этапе происходит создание массивов (одномерных (вектор) и двумерных (матрица)) 
и присвоение массива к переменной

In [22]:
arr_common_vector = np.array([1, 3, 5, 7, 9, 11])
arr_common_vector

array([ 1,  3,  5,  7,  9, 11])

In [17]:
arr_common_matrix = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
arr_common_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr_class = np.array(['Crown', 'Branch', 'Foliage', 'Root', 'trunk'])
arr_class

array(['Crown', 'Branch', 'Foliage', 'Root', 'trunk'], dtype='<U7')

In [ ]:
Можно сначала создать массив через обычный питон, потом воспользоваться библиотекой numpy
и создать массив на её основе

In [18]:
arr_test = [1, 1, 0.5, 0.4, 0.3, 0.2, 0.1, 0]
np_arr_test = np.array(arr_test)
np_arr_test

array([1. , 1. , 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

С использованием функций zeros, ones, arange или аналогичных

Zeros создаёт массив указанной в параметрамх размерности и заполняет его нулями

In [24]:
arr_zeros_1_3 = np.zeros((1, 3))
arr_zeros_1_3

array([[0., 0., 0.]])

In [25]:
arr_zeros_3_1 = np.zeros((3,1))
arr_zeros_3_1

array([[0.],
       [0.],
       [0.]])

In [ ]:
Ones создаёт массив указанной в параметрах размерности и заполняет его единицами

In [28]:
arr_ones_5_1_2 = np.ones((5, 1, 2))
arr_ones_5_1_2

array([[[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]]])

In [29]:
arr_ones_1_5_2 = np.ones((1, 5, 2))
arr_ones_1_5_2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
arr_ones2_3 = np.ones((2, 3))
arr_ones2_3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr_ones2 = np.ones(2)
arr_ones2

array([1., 1.])

Arange создаёт массив по правилу: если параметр 1 число, то создает массив от 0 до нашего числа
не включительно с шагом 1
если параметров 2, то создает массив от первого числа до второго не включительно с шагом 1
если параметром 3, то создает массив в промежутке от одного числа до другого с шагом указанным
3 параметром. От какого числа до какого зависит от знака 3 параметра. Если он положительный, то
от первого параметра до второго не включительно.
Если он отрицательный, то от второго до первого не включительно

In [137]:
arr_arange_pos = np.arange(10, 11, 0.1)
arr_arange_pos

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

In [48]:
arr_arange_neg = np.arange(11, 10, -0.0001)
arr_arange_neg

array([11.    , 10.9999, 10.9998, ..., 10.0003, 10.0002, 10.0001],
      shape=(10000,))

Демонстрация атрибутов:
вывод формы (shape) и типа данных (dtype) для одного из массивов

shape показывает размерность массива. Ниже массив представляет из себя вектор из 10000 элементов
dtype показывет тип массива (элементы лежащие в массиве). Ниже массив содержащий вещественные числа

In [49]:
arr_arange_neg.shape

(10000,)

In [50]:
arr_arange_neg.dtype

dtype('float64')

Примеры индексирования и срезов

Получение отдельного элемента:

Индекс в массиве это номер элемента в массиве. Индекс начинается с 0.

In [55]:
arr_common_vector

array([ 1,  3,  5,  7,  9, 11])

In [56]:
arr_common_vector[3]

np.int64(7)

In [57]:
arr_common_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

В двумерном массиве элемент имеет 2 индекса. Индекс по строкам и индекс по столбцам.
Ниже приведен пример нахождения значения в матрице по первому индексу 1 (2 строка) и
второму индексу 2 (3 столбец) и наоборот (3 строка и  2 столбец)

In [61]:
arr_common_matrix[1][2]

np.int64(6)

In [62]:
arr_common_matrix[2, 1]

np.int64(8)

Извлечение подмассива с помощью среза

In [69]:
arr_vector = np.arange(10)
arr_vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr_cut берет срез от индекса 2 до индекса 7 не включительно

In [70]:
arr_cut = arr_vector[2:7]
arr_cut

array([2, 3, 4, 5, 6])

arr_cut2 берет срез от индекса 0 до индекса 10-2 = 8 не включительно

In [75]:
arr_cut2 = arr_vector[:-2]
arr_cut2

array([0, 1, 2, 3, 4, 5, 6, 7])

arr_cut3 берет срез от индекса 10-2 = 8 до конца массива

In [112]:
arr_cut3 = arr_vector[-2:]
arr_cut3

array([8, 9])

In [116]:
arr_matrix = np.array([[1,   2,   3,   5,   7,   8],
                       [5,   8,   13,  14,  16,  18],
                       [1,   4,   5,   1,   2,   1],
                       [2,   3,   5,   6,   1,   7],
                       [124, 344, 455, 261, 412, 471]])
arr_matrix

array([[  1,   2,   3,   5,   7,   8],
       [  5,   8,  13,  14,  16,  18],
       [  1,   4,   5,   1,   2,   1],
       [  2,   3,   5,   6,   1,   7],
       [124, 344, 455, 261, 412, 471]])

arr_cut_matrix берет срез по строкам от индекса 1 до индекса 4 не включительно
и срез по столбцам от индекса 1 до индекса 5 не включительно

In [109]:
arr_cut_matrix = arr_matrix[1:4, 1:5]
arr_cut_matrix

array([[ 8, 13, 14, 16],
       [ 4,  5,  1,  2],
       [ 3,  5,  6,  1]])

Ниже происходит присвоение данному срезу значение 0

In [110]:
arr_matrix[1:4, 1:5] =  0
arr_matrix

array([[  1,   2,   3,   5,   7,   8],
       [  5,   0,   0,   0,   0,  18],
       [  1,   0,   0,   0,   0,   1],
       [  2,   0,   0,   0,   0,   7],
       [124, 344, 455, 261, 412, 471]])

Примеры векторных операций и базовых статистик:

поэлементное сложение и умножение массивов

In [117]:
first_arr = np.arange(10)
first_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ниже каждый элемент в массиве поэлементно возводится в квадрат

In [118]:
second_arr = np.arange(10) ** 2
second_arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Поэлементное сложение массивов (значение с индексом 0 первого массива складывается с индексом 0 второго массива
значение с индексом 1 первого массива складывается с индексом 1 второго массива и так далее. В результате получается новый массив - результат сложения двух массивов)

In [123]:
result_add = first_arr + second_arr
result_add

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

Аналогично сложению, происходит только смена операции

In [122]:
result_sub = first_arr - second_arr
result_sub

array([  0,   0,  -2,  -6, -12, -20, -30, -42, -56, -72])

Анологтчно сложению, происходит только смена операции

In [124]:
result_mult = first_arr * second_arr
result_mult

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

Готовый метод в numpy, который сразу находит сумму массива

In [125]:
np.sum(result_add)

np.int64(330)

Готовый метод в numpy, который сразу находит среднее значение в массиве

In [126]:
np.mean(result_add)

np.float64(33.0)

Найти выборочное среднее, исправленную среднее квадратическое отклонение для выборок заданных ниже

In [131]:
x_i = np.array([ 3.2,  4.4,  5.0,  6.7,  7.5,  8.1])
n_i = np.array([ 3,    5,    3,    5,    1,    3 ])
w_i = np.array([ 0.15, 0.25, 0.15, 0.25, 0.05, 0.15])

Xch = (np.sum(x_i *  n_i))/np.sum(n_i)
Xch

np.float64(5.595)

In [132]:
import math
SquareS = np.sum( np.pow(x_i - Xch, 2) * n_i) / ( np.sum(n_i) - 1 ) 
SquareS 

np.float64(2.8404999999999996)

In [133]:
S = math.sqrt(SquareS)
S

1.685378295813732